version: '3.1'

services:
  web:
    image: php:8.0-apache
    container_name: php_web
    build:
      context: .
      dockerfile: Dockerfile-php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    # Bart beun oplossing voor MAC OS
    # platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 674392
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: thomvm
      MYSQL_PASSWORD: 7830984
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 674392
    depends_on:
      - db

volumes:
  db_data:

jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental
    ports:
        - 8000:8000
    volumes:
        - .:/srv/jekyll